/*
* Action types
*/
export const AUTH_FETCHING = 'AUTH_FETCHING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FETCHING_BUSINESSES = 'FETCHING_BUSINESSES';
export const GET_ALL_BUSINESSES_SUCCESS = 'GET_ALL_BUSINESSES_SUCCESS';
export const GET_ONE_BUSINESS_SUCCESS = 'GET_ONE_BUSINESS_SUCCESS';
export const GET_ONE_BUSINESS_FAIL = 'GET_ONE_BUSINESS_FAIL';
export const ADD_BUSINESS_SUCCESS = 'ADD_BUSINESS_SUCCESS';
export const ADD_BUSINESS_FAIL = 'ADD_BUSINESS_FAIL';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const GET_ALL_REVIEWS_FAIL = 'GET_ALL_REVIEWS_FAIL';
export const DELETE_BUSINESS_SUCCESS = 'DELETE_BUSINESS_SUCCESS';
export const DELETE_BUSINESS_FAIL = 'DELETE_BOOK_FAIL';
export const EDIT_BUSINESS_SUCCESS = 'EDIT_BUSINESS_SUCCESS';
export const PASSWORD_FETCHING = 'PASSWORD_FETCHING';
export const REQUEST_RESET_SUCCESS = 'REQUEST_RESET_SUCCESS';
export const REQUEST_RESET_FAIL = 'REQUEST_RESET_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
